""" Agent Values """
DIRECTIONS = ((0,1), (1,0), (0,-1), (-1,0))

""" Environment Values """
SCALE = 3
ROW_COUNT = 80
COLUMN_COUNT = 80
BOMB_COUNT = 10
BOOST_COUNT = 40
INITIAL_SPEED = 3
NUM_PLAYERS = 2

""" Tile Values """
TEMP = -1
UNOCCUPIED = 0
PASSED = 1
OCCUPIED = 2
BOMB = 3
BOOST = 4

""" Rendering Values """
SPRITE_SCALING = 0.33
WIDTH = 5
HEIGHT = 5
MARGIN = 1
SCREEN_WIDTH = (WIDTH + MARGIN) * COLUMN_COUNT + MARGIN
SCREEN_HEIGHT = (HEIGHT + MARGIN) * ROW_COUNT + MARGIN
SCREEN_TITLE = "yoooo"
