""" Agent Values """
DIRECTIONS = ((0,1), (1,0), (0,-1), (-1,0))

""" Environment Values """
ROW_COUNT = 80
COLUMN_COUNT = 80
BOMB_COUNT = 10
BOOST_COUNT = 40

""" Tile Values """
TEMP = -1
UNOCCUPIED = 0
PASSED = 1
OCCUPIED = 2
BOMB = 3
BOOST = 4

""" Tile Size """
SPRITE_SCALING = 0.5
WIDTH = 10
HEIGHT = 10
MARGIN = 0


"""Progress Bar Values"""
HEIGHT_PROGRESSBAR = 20
HEIGHT_PROGRESSBAR_GAP = 10
WIDTH_PROGRESSBAR = 200
HEIGHT_PROGRESSBAR_DIV = (HEIGHT_PROGRESSBAR + HEIGHT_PROGRESSBAR_GAP) * 4

"""Screen Values"""
WIDTH_SCREEN = (WIDTH + MARGIN) * COLUMN_COUNT + MARGIN
HEIGHT_GAME_DIV = (WIDTH + MARGIN) * ROW_COUNT + MARGIN
HEIGHT_SCREEN = HEIGHT_GAME_DIV + HEIGHT_PROGRESSBAR_DIV
SCREEN_TITLE = "Paper IO Game"
